### ISSUE TITLE
jtopo demo v1.4.6 在线编辑器定位线不消失

### ISSUE THREAD

**Issue by bzh923** [wondery/jtopo-demos#4]
![pic1](https://github.com/wondery/jtopo-demos/assets/41609756/2ed2a676-f0e4-4ec1-b02a-fbccddd6f69c)

在线编辑器默认模式下拖拽节点会画出定位线，但是拖拽结束定位线没有消失，如果此时再拖拽画布定位线即不消失也不随节点移动。
是否可以隐藏定位线，怎么隐藏？

**Comment by wondery** [comment]
这可能是1.4.6版本里的一个bug，
1.4.6版本的解决办法试试如下：
// 先隐藏掉
editor.hideGuidLine();
// 重新显示方法（什么都不做）
editor.showGuildLine = function(){};




在 2024年2月22日 ***@***.***> 写道：


pic1.PNG (view on web)
在线编辑器默认模式下拖拽节点会画出定位线，但是拖拽结束定位线没有消失，如果此时再拖拽画布定位线即不消失也不随节点移动。
 是否可以隐藏定位线，怎么隐藏？

**Comment by bzh923** [comment]
thanks, it works.
同时还发现了个拼写错误，一会是"Guid"一会是“Guild”      ：）

**Comment by wondery** [comment]
是的，最新版本里已经移除了这个，增加了新的辅助对齐功能。


在 2024年2月23日 ***@***.***> 写道：


thanks, it works.
 同时还发现了个拼写错误，一会是"Guid"一会是“Guild” ：）
